### ISSUE TITLE
Jak wklejam linka do naszej strony jak jestem zalogowany, to już nie jestem zalogowany

### ISSUE THREAD

**Issue by goianu** [ddave666/shop_crawler#3]
Jestem zalogowany, wklejam w adres http://olchovny.ddns.net:8180/shop_crawler/ i już nie jestem zalogowany

**Comment by ddave666** [comment]
Problem z dodawaniem cookiesow. W wieczornym buildzie juz poprawiony - trzeba niestety potwierdzic po zalogowaniu ze ok. Chodzi o to ze uzytkownik musi cokolwiek kliknac po zalogowaniu przez FB zeby mogl dostac cookiesa. Inaczej sie ich przepchnac nie da:(
